# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170106_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
