# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170106_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gratitude',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Gratitude'),
            preserve_default=False,
        ),
    ]
