# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entry_is_published'),
        ('app', '0003_comment_gratitude'),
    ]

    operations = [
    ]
